PR_Top_Service_MVC/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PR_Top_Service_MVC.Models;

namespace PR_Top_Service_MVC.Controllers
{

    [Authorize]
    public class PeopleController : Controller
    {
        private readonly TopServiceBDOContext _context;

        public PeopleController(TopServiceBDOContext context)
        {
            _context = context;
        }

        // GET: People
        public async Task<IActionResult> Index()
        {
            var topServiceBDOContext = _context.People.Include(p => p.IdDepartmentNavigation);
            return View(await topServiceBDOContext.ToListAsync());
        }

        public async Task<IActionResult> ProfessionalArea(int id)
        {
            IQueryable<Postulation> person = from Postulation in _context.Postulations.Include(a => a.IdProfessionalNavigation.IdProfesionalNavigation)
                                        join Profesional in _context.Profesionals on Postulation.IdProfessional equals Profesional.IdProfesional
                                        join AreaAttribute in _context.AreaProfesional on Profesional.IdProfesional equals AreaAttribute.IdProfesional
                                        join JobArea in _context.JobArea on AreaAttribute.idArea equals JobArea.idArea
                                        join Person in _context.People on Profesional.IdProfesional equals Person.IdPerson
                                        where Postulation.idArea == id && Postulation.Status == 2
                                        select Postulation;



            return View(await person.ToListAsync());
        }


        // GET: People/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.People == null)
            {
                return NotFound();
            }

            var person = await _context.People
                .Include(p => p.IdDepartmentNavigation)
                .FirstOrDefaultAsync(m => m.IdPerson == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // GET: People/Create
        public IActionResult Create()
        {
            ViewData["IdDepartment"] = new SelectList(_context.Departments, "IdDepartment", "IdDepartment");
            return View();
        }

        // POST: People/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdPerson,Name,LastName,SecondLastName,IdDepartment,status,deleted")] Person person)
        {
            if (ModelState.IsValid)
            {
                _context.Add(person);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdDepartment"] = new SelectList(_context.Departments, "IdDepartment", "IdDepartment", person.IdDepartment);
            return View(person);
        }

        // GET: People/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.People == null)
            {
                return NotFound();
            }

            var person = await _context.People.FindAsync(id);
            if (person == null)
            {
                return NotFound();
            }
            ViewData["IdDepartment"] = new SelectList(_context.Departments, "IdDepartment", "IdDepartment", person.IdDepartment);
            return View(person);
        }

        // POST: People/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdPerson,Name,LastName,SecondLastName,IdDepartment,status,deleted")] Person person)
        {
            if (id != person.IdPerson)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(person);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonExists(person.IdPerson))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdDepartment"] = new SelectList(_context.Departments, "IdDepartment", "IdDepartment", person.IdDepartment);
            return View(person);
        }

        // GET: People/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.People == null)
            {
                return NotFound();
            }

            var person = await _context.People
                .Include(p => p.IdDepartmentNavigation)
                .FirstOrDefaultAsync(m => m.IdPerson == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // POST: People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.People == null)
            {
                return Problem("Entity set 'TopServiceBDOContext.People'  is null.");
            }
            var person = await _context.People.FindAsync(id);
            if (person != null)
            {
                _context.People.Remove(person);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonExists(int id)
        {
          return (_context.People?.Any(e => e.IdPerson == id)).GetValueOrDefault();
        }
    }
}

PR_Top_Service_MVC/Controllers/ServiceReceiptController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PR_Top_Service_MVC.Models;

namespace PR_Top_Service_MVC.Controllers
{
    [Authorize]
    public class ServiceReceiptController : Controller
    {
        private readonly TopServiceBDOContext _context;

        public ServiceReceiptController(TopServiceBDOContext context)
        {
            _context = context;
        }

        // GET: ServiceReceipt
        public async Task<IActionResult> Index()
        {
            return _context.ServiceReceipt != null ?
                        View(await _context.ServiceReceipt.ToListAsync()) :
                        Problem("Entity set 'TopServiceBDOContext.ServiceReceipt'  is null.");
        }


        public async Task<IActionResult> Receipt()
        {
            IQueryable<Service> service = from Service in _context.Services.Include(a => a.IdCostumerNavigation).Include(a => a.IdCostumerNavigation.IdCostumerNavigation).Include(a => a.Receipt)

                                          where  Service.IdCostumer == UserConfig.userLogin.IdUser
                                          select Service;

            return View(await service.ToListAsync());
        }
        // GET: ServiceReceipt/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ServiceReceipt == null)
            {
                return NotFound();
            }

            var serviceReceipt = await _context.ServiceReceipt
                .FirstOrDefaultAsync(m => m.IdService == id);
            if (serviceReceipt == null)
            {
                return NotFound();
            }

            return View(serviceReceipt);
        }

        // GET: ServiceReceipt/Create
        public IActionResult Create()
        {
          
            ViewData["IdAdmin"] = new SelectList(_context.Admins, "IdAdmin", "IdAdmin");
            ViewData["IdCostumer"] = new SelectList(_context.Costumers.OrderBy(x=>x.Ci), "IdCostumer", "Ci");
           

            return View();
        }

        // POST: ServiceReceipt/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, [Bind("IdService,IdAdmin,IdProfessional,IdCostumer,deleted,Description,Date,Status,IdReceipt,DescriptionReceipt,Total")] ServiceReceipt serviceReceipt)
        {
            if (ModelState.IsValid)
            {
                Service s = new()
                {
                    IdAdmin = UserConfig.userLogin.IdUser,
                    IdProfessional = id,
                    IdCostumer = serviceReceipt.IdCostumer,
                    
                    Description = serviceReceipt.Description,
                    Date = serviceReceipt.Date,
                    Status = 1,
                    deleted = 0
                };
                _context.Add(s);
                await _context.SaveChangesAsync();

                Receipt r = new()
                {
                    IdReceipt = s.IdService,
                    Description = serviceReceipt.DescriptionReceipt,
                    Total = serviceReceipt.Total


                };
                _context.Add(r);
                await _context.SaveChangesAsync();

            }
          
            ViewData["IdAdmin"] = new SelectList(_context.Admins, "IdAdmin", "IdAdmin", serviceReceipt.IdAdmin);
            ViewData["IdCostumer"] = new SelectList(_context.Costumers.OrderBy(x => x.Ci), "IdCostumer", "Ci", serviceReceipt.IdCostumer);
            return RedirectToAction("Index", "Service");
        }

        // GET: ServiceReceipt/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ServiceReceipt == null)
            {
                return NotFound();
            }

            var serviceReceipt = await _context.ServiceReceipt.FindAsync(id);
            if (serviceReceipt == null)
            {
                return NotFound();
            }
            return View(serviceReceipt);
        }

        // POST: ServiceReceipt/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdService,IdAdmin,IdProfessional,IdCostumer,Name,Description,Date,Status,IdReceipt,DescriptionReceipt,Total")] ServiceReceipt serviceReceipt)
        {
            if (id != serviceReceipt.IdService)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(serviceReceipt);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServiceReceiptExists(serviceReceipt.IdService))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(serviceReceipt);
        }

        // GET: ServiceReceipt/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ServiceReceipt == null)
            {
                return NotFound();
            }

            var serviceReceipt = await _context.ServiceReceipt
                .FirstOrDefaultAsync(m => m.IdService == id);
            if (serviceReceipt == null)
            {
                return NotFound();
            }

            return View(serviceReceipt);
        }

        // POST: ServiceReceipt/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ServiceReceipt == null)
            {
                return Problem("Entity set 'TopServiceBDOContext.ServiceReceipt'  is null.");
            }
            var serviceReceipt = await _context.ServiceReceipt.FindAsync(id);
            if (serviceReceipt != null)
            {
                _context.ServiceReceipt.Remove(serviceReceipt);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ServiceReceiptExists(int id)
        {
            return (_context.ServiceReceipt?.Any(e => e.IdService == id)).GetValueOrDefault();
        }
    }
}

PR_Top_Service_MVC/Views/People/Create.cshtml
@model PR_Top_Service_MVC.Models.Person

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondLastName" class="control-label"></label>
                <input asp-for="SecondLastName" class="form-control" />
                <span asp-validation-for="SecondLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdDepartment" class="control-label"></label>
                <select asp-for="IdDepartment" class ="form-control" asp-items="ViewBag.IdDepartment"></select>
            </div>
            <div class="form-group">
                <label asp-for="status" class="control-label"></label>
                <input asp-for="status" class="form-control" />
                <span asp-validation-for="status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="deleted" class="control-label"></label>
                <input asp-for="deleted" class="form-control" />
                <span asp-validation-for="deleted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

PR_Top_Service_MVC/Views/People/Delete.cshtml
@model PR_Top_Service_MVC.Models.Person

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Person</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SecondLastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SecondLastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.deleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.deleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdDepartmentNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdDepartmentNavigation.IdDepartment)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdPerson" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PR_Top_Service_MVC/Views/People/Details.cshtml
@model PR_Top_Service_MVC.Models.Person

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Person</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SecondLastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SecondLastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.deleted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.deleted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdDepartmentNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdDepartmentNavigation.IdDepartment)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.IdPerson">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PR_Top_Service_MVC/Views/People/Edit.cshtml
@model PR_Top_Service_MVC.Models.Person

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdPerson" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondLastName" class="control-label"></label>
                <input asp-for="SecondLastName" class="form-control" />
                <span asp-validation-for="SecondLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdDepartment" class="control-label"></label>
                <select asp-for="IdDepartment" class="form-control" asp-items="ViewBag.IdDepartment"></select>
                <span asp-validation-for="IdDepartment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="status" class="control-label"></label>
                <input asp-for="status" class="form-control" />
                <span asp-validation-for="status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="deleted" class="control-label"></label>
                <input asp-for="deleted" class="form-control" />
                <span asp-validation-for="deleted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

PR_Top_Service_MVC/Views/People/Index.cshtml
@model IEnumerable<PR_Top_Service_MVC.Models.Person>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SecondLastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.deleted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdDepartmentNavigation)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SecondLastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.deleted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdDepartmentNavigation.IdDepartment)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.IdPerson">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.IdPerson">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.IdPerson">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

PR_Top_Service_MVC/Views/People/ProfessionalArea.cshtml
@model IEnumerable<PR_Top_Service_MVC.Models.Postulation>

@{
    ViewData["Title"] = "Index";
}

<h1>Profesionales</h1>


<div class="row row-cols-1 row-cols-md-2 g-4">
    @foreach (var item in Model)
    {
        <div class="col">
        <div class="card text-center" style="width: 18rem;">
        <div class="card-body">
        <h3 class="card-title">Nombre: @(item.IdProfessionalNavigation.IdProfesionalNavigation.Name +" " +  item.IdProfessionalNavigation.IdProfesionalNavigation.LastName + " " + item.IdProfessionalNavigation.IdProfesionalNavigation.SecondLastName)</h3>
        <p class="card-text">Experiencia Laboral: @item.WorkExperience</p>
         <p class="card-text">Titulos: @item.ProfessionalTitles</p>
          <p class="card-text">Certificaciones: @item.Certification</p>
                    @if (User.IsInRole("Admin"))
                    { 
                        <a asp-action="Create" asp-controller="ServiceReceipt" asp-route-id="@item.IdProfessional" class="btn btn-primary">Nuevo Servicio</a>
                        
                    }
                    @if (User.IsInRole("Client"))
                    {
                        <a asp-action="Create" asp-controller="Quotation" asp-route-id="@item.IdProfessional" class="btn btn-primary">Solicitar Cotizacion</a>
                    }

         
        </div>
        </div>
        </div>
    }
</div>